name: "wordcloud"

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  newCloud:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Set env vars
      run: |
        echo ::set-env name=REPOSITORY::${{ github.repository }}
        echo ::set-env name=EVENT_PR_NUMBER::${{ github.event.pull_request.number }}
        echo ::set-env name=EVENT_USER_LOGIN::${{ github.event.pull_request.user.login }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        gem install octokit -N --silent
        pip install wordcloud
    - name: New Word Cloud Generation
      run: |
        ruby <<- EORUBY
          require './wordcloud/runner'
          
          Runner.new(
            github_token: '${{ secrets.GITHUB_TOKEN }}',
            issue_number: ENV.fetch('EVENT_PR_NUMBER'),
            issue_title: '${{ github.event.pull_request.title }}',
            repository: ENV.fetch('REPOSITORY'),
            user: ENV.fetch('EVENT_USER_LOGIN'),
          ).new_cloud
        EORUBY
